config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from django.views import defaults as default_views
from django.views.generic import TemplateView

from peter_lists.projects import views as proj_view

urlpatterns = [
    # Django Admin, use {% url 'admin:index' %}
    path(settings.ADMIN_URL, admin.site.urls),
    # User management
    path("users/", include("peter_lists.users.urls", namespace="users")),
    path("accounts/", include("allauth.urls")),
    # Your stuff: custom urls includes go here
    path(route="", view=proj_view.ProjHomeView, name="home"),
    path("blog/", include("peter_lists.blog.urls"), name="blog"),
    path("books/", include("peter_lists.books.urls"), name="books"),
    path("lego/", include("peter_lists.lego.urls"), name="lego"),
    path("origami/", include("peter_lists.origami.urls"), name="origami"),
    path("passwd/", include("peter_lists.passwd.urls"), name="passwd"),
    path("projects/", include("peter_lists.projects.urls"), name="projects"),
    path("recipes/", include("peter_lists.recipes.urls"), name="recipes"),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        path(
            "400/",
            default_views.bad_request,
            kwargs={"exception": Exception("Bad Request!")},
        ),
        path(
            "403/",
            default_views.permission_denied,
            kwargs={"exception": Exception("Permission Denied")},
        ),
        path(
            "404/",
            default_views.page_not_found,
            kwargs={"exception": Exception("Page not Found")},
        ),
        path("500/", default_views.server_error),
    ]
    if "debug_toolbar" in settings.INSTALLED_APPS:
        import debug_toolbar

        urlpatterns = [path("__debug__/", include(debug_toolbar.urls))] + urlpatterns

peter_lists/blog/urls.py
from django.urls import path
from . import views

app_name = "blog"
urlpatterns = [
    path(route="", view=views.BlogHome, name="home"),
    path(route="list/", view=views.BlogListView.as_view(), name="list"),
    path(route="list/tag/<tag_name>", view=views.BlogTagListView.as_view(), name="tag_list"),
    path(route="tags/", view=views.BlogAllTagsView, name="all_tags"),
    path(route="detail/<int:pk>/", view=views.BlogDetailView.as_view(), name="detail"),

    path(route="add/", view=views.BlogCreateView.as_view(), name="add"),
    path(route="update/<int:pk>/", view=views.BlogUpdateView.as_view(), name="update"),
    path(route="delete/<int:pk>/", view=views.BlogDeleteView.as_view(), name="delete"),
]

peter_lists/books/urls.py
from django.urls import path
from .views import views_books, views_authors, views_publishers

app_name = "books"
urlpatterns = [
    path(route="", view=views_books.BookHome, name="home"),
    path(route="list/", view=views_books.BookListView.as_view(), name="list"),
    path(route="detail/<slug:slug>/", view=views_books.BookDetailView.as_view(), name="detail"),

    path(route="add/", view=views_books.BookCreateView.as_view(), name="add"),
    path(route="update/<slug:slug>/", view=views_books.BookUpdateView.as_view(), name="update"),
    path(route="delete/<slug:slug>/", view=views_books.BookDeleteView.as_view(), name="delete"),

    path(route="booktype/", view=views_books.BookTypeListView.as_view(), name="booktype_list"),
    path(route="booktype/books/<int:type_id>/", view=views_books.BookTypeBookListView.as_view(),
         name="booktype_book_list"),

    # Authors
    path(route="authors/", view=views_authors.AuthorListView.as_view(), name="author_list"),
    path(route="author/books/<author>/", view=views_authors.AuthorBookListView.as_view(), name="author_book_list"),

    # Publishers
    path(route="publishers/", view=views_publishers.PublisherListView.as_view(), name="publishers_list"),
    path(route="publisher/books/<publisher>/", view=views_publishers.PublisherBookListView.as_view(),
         name="publisher_book_list"),
]

peter_lists/lego/urls.py
from django.urls import path
from . import views

app_name = "lego"
urlpatterns = [
    path(route="", view=views.LegoHome, name="home"),
    path(route="list/", view=views.LegoListView.as_view(), name="list"),
]

peter_lists/books/models.py
from django.conf import settings
from django.db import models
from model_utils.models import TimeStampedModel
from django.utils.translation import gettext_lazy as _
from django.template.defaultfilters import slugify
from django.urls import reverse


class Author(TimeStampedModel):
    name = models.CharField("Author Name", max_length=250)
    slug = models.SlugField(unique=True, default="_", blank=False)

    class Meta:
        ordering = ["name"]

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse("books:author_list")

    def save(self, *args, **kwargs):
        if (not self.slug) or (self.slug == "_"):
            self.slug = slugify(self.name)
        return super().save(*args, **kwargs)


class BookType(TimeStampedModel):
    type = models.CharField("Book Type", max_length=25)

    class Meta:
        ordering = ["type"]

    def __str__(self):
        return self.type

    def get_absolute_url(self):
        return reverse("books:booktype_list")


class Publisher(TimeStampedModel):
    name = models.CharField("Book Publisher", max_length=250)
    slug = models.SlugField(unique=True, default="_", blank=False)

    class Meta:
        ordering = ["name"]

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse("books:publishers_list")

    def save(self, *args, **kwargs):
        if (not self.slug) or (self.slug == "_"):
            self.slug = slugify(self.name)
        return super().save(*args, **kwargs)


class BookManager(models.Manager):
    def get_queryset(self):
        return super(BookManager, self).get_queryset().filter(type=3)

class Book(TimeStampedModel):
    class StatusChoices(models.TextChoices):
        COMPLETED = "RD", _("Completed")
        READING = "RG", _("Reading")
        TO_READ = "TR", _("To read")
        NEXT = "NT", _("Next")
        BROWSING = "BG", _("Browsing")
        REFERENCE = "RE", _("Reference")
        GIVEN_UP = "GU", _("Given-up")
        WISH_LIST = "WL", _("Wishlist")
        INACTIVE = "IA", _("Inactive")
        UNKOWN = "UK", _("Unknown")

    class FormChoices(models.TextChoices):
        PAPERBACK = "PB", _("Paperback")
        HARDBACK = "HB", _("Hardback")
        KINDLE = "KI", _("Kindle")
        MAGAZINE = "MA", _("Magazine")
        WISH_LIST = "WL", _("Wishlist")
        OTHER = "OT", _("Other")

    title = models.CharField("Book Title", max_length=250)
    subtitle = models.CharField("Subtitle", max_length=250, blank=True)
    author = models.ForeignKey("Author", on_delete=models.CASCADE)
    description = models.TextField("Description", blank=True)
    isbn = models.CharField("ISBN Number", max_length=25, blank=True)
    publisher = models.ForeignKey("Publisher", on_delete=models.CASCADE)
    pages = models.IntegerField("No. of Pages", default=0)
    type = models.ForeignKey("BookType", on_delete=models.CASCADE)
    form = models.CharField(
        "Form",
        max_length=2,
        choices=FormChoices.choices,
        default=FormChoices.OTHER,
    )
    status = models.CharField(
        "Status",
        max_length=2,
        choices=StatusChoices.choices,
        default=StatusChoices.UNKOWN,
    )
    slug = models.SlugField(unique=True, default="_", blank=False)
    creator = models.ForeignKey(
        settings.AUTH_USER_MODEL, null=True, on_delete=models.SET_NULL
    )
    tag = models.CharField("Tag", max_length=100, blank=True, default="none, ")
    rating = models.IntegerField("Rating (1-10)", default=0)
    pct_read = models.IntegerField("Pct% Read", default=0)

    class Meta:
        ordering = [
            "title",
            "subtitle",
        ]

    books = models.Manager()
    cook_books = BookManager()

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse("books:list")

    def save(self, *args, **kwargs):  # new
        if (not self.slug) or (self.slug == "_"):
            self.slug = slugify(self.title)
        return super().save(*args, **kwargs)

peter_lists/lego/models.py
from django.db import models
from model_utils.models import TimeStampedModel


class LegoSet(TimeStampedModel):
    name = models.CharField("Name of LEGO Set", max_length=255)

peter_lists/blog/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.mixins import PermissionRequiredMixin
from django.views.generic import (
    ListView,
    DetailView,
    CreateView,
    UpdateView,
    DeleteView,
)
from django.shortcuts import render
from django.db.models import Count
from django.db.models.functions import Trim, Lower
from django.urls import reverse_lazy
from .models import Blog
from .forms import EditBlogForm


def tag_count(blog_user, topn=0):
    # TODO Move to model manager
    raw_tags = (
        Blog.blog.filter(user=blog_user)
        .order_by("tag")
        .values("tag")
        .annotate(count=Count("tag"), tag_new=Trim(Lower("tag")))
    )
    count_tags = dict()

    # TODO Split by tags with "," and those without
    for record in raw_tags:
        for tag in record["tag_new"].split(","):
            k = tag.strip()
            if len(k) > 0:
                count_tags[k] = count_tags.get(k, 0) + record["count"]

    # TODO Sort by value (desc) and then key (ascend) for common values
    if topn == 0:
        return {
            k: count_tags[k]
            for k in sorted(count_tags, key=count_tags.get, reverse=True)
        }
    else:
        return {
            k: count_tags[k]
            for k in sorted(count_tags, key=count_tags.get, reverse=True)[:topn]
        }


# Create your views here.
def BlogHome(request):
    blog_all = Blog.blog.filter(user=request.user)
    blogs = blog_all.order_by("-modified")[:3]
    blog_count = blog_all.count()
    tag_sorted = tag_count(request.user, topn=5)
    return render(
        request,
        "blog/blog_home.html",
        {"blogs": blogs, "tags": tag_sorted, "blog_count": blog_count},
    )


class BlogListView(PermissionRequiredMixin, ListView):
    model = Blog
    paginate_by = 3
    template_name = "blog/blog_list.html"
    permission_required = "blog.view_blog"

    def get_queryset(self):
        return Blog.blog.filter(user=self.request.user)


def BlogAllTagsView(request):
    # TODO turn into ListView with paginate
    tag_sorted = tag_count(request.user)
    return render(request, "blog/blog_tags.html", {"tags": tag_sorted})


class BlogTagListView(PermissionRequiredMixin, ListView):
    model = Blog
    paginate_by = 3
    template_name = "blog/blog_list.html"
    permission_required = "blog.view_blog"

    def get_queryset(self):
        return Blog.blog.filter(tag__contains=self.kwargs["tag_name"], user=self.request.user)


class BlogDetailView(PermissionRequiredMixin, DetailView):
    model = Blog
    template_name = "blog/blog_detail.html"
    permission_required = "blog.view_blog"


class BlogCreateView(PermissionRequiredMixin, LoginRequiredMixin, CreateView):
    form_class = EditBlogForm
    model = Blog
    action = "Add"
    template_name = "blog/blog_form.html"
    permission_required = "blog.add_blog"


class BlogUpdateView(PermissionRequiredMixin, LoginRequiredMixin, UpdateView):
    form_class = EditBlogForm
    model = Blog
    action = "Edit"
    template_name = "blog/blog_form.html"
    permission_required = "blog.change_blog"


class BlogDeleteView(PermissionRequiredMixin, LoginRequiredMixin, DeleteView):
    model = Blog
    success_url = reverse_lazy("blog:list")
    permission_required = "blog.delete_blog"

peter_lists/books/views/views_authors.py
from django.core.paginator import Paginator
from django.views.generic import ListView
from django.shortcuts import get_object_or_404
from peter_lists.books.models import Author, Book


class AuthorListView(ListView):
    model = Author
    paginate_by = 25
    template_name = "books/author_list.html"


class AuthorBookListView(ListView):
    model = Book
    paginate_by = 25
    template_name = "books/book_list.html"

    def get_queryset(self):
        author = get_object_or_404(Author, name=self.kwargs["author"])
        return Book.books.filter(author=author)

    def get_context_data(self, **kwargs):
        # Call the base implementation first to get a context
        context = super().get_context_data(**kwargs)
        # Add in extra data
        author = get_object_or_404(Author, name=self.kwargs["author"])
        context['head'] = f"For Author = {author}"
        return context

peter_lists/books/views/views_books.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import (
    ListView,
    DetailView,
    CreateView,
    UpdateView,
    DeleteView,
)
from django.db.models import Count
from django.shortcuts import get_object_or_404, render
from django.urls import reverse_lazy
from peter_lists.books.models import Book, BookType, Author, Publisher
from peter_lists.books.forms import EditBookForm


def BookHome(request):
    books = Book.books.order_by("-modified")[:3]
    authors = Author.objects.order_by("-modified")[:3]
    publishers = Publisher.objects.order_by("-modified")[:3]
    return render(
        request,
        "books/books_home.html",
        {"books": books, "authors": authors, "publishers": publishers},
    )


class BookListView(ListView):
    model = Book
    paginate_by = 25
    template_name = "books/book_list.html"


class BookDetailView(DetailView):
    model = Book
    template_name = "books/book_detail.html"


class BookCreateView(LoginRequiredMixin, CreateView):
    form_class = EditBookForm
    model = Book
    action = "Add"
    template_name = "books/book_form.html"


class BookUpdateView(LoginRequiredMixin, UpdateView):
    form_class = EditBookForm
    model = Book
    action = "Edit"
    template_name = "books/book_form.html"


class BookDeleteView(LoginRequiredMixin, DeleteView):
    model = Book
    success_url = reverse_lazy("books:list")


class BookTypeListView(ListView):
    model = BookType
    result = (
        Book.books.values("type", "type__type")
        .order_by("type__type")
        .annotate(count=Count("type__type"))
        .order_by("-count")[:10]
    )
    template_name = "books/booktype_list.html"


class BookTypeBookListView(ListView):
    model = BookType
    paginate_by = 25
    template_name = "books/book_list.html"

    def get_queryset(self):
        book_type = get_object_or_404(BookType, id=self.kwargs["type_id"])
        return Book.books.filter(type=book_type.id)

    def get_context_data(self, **kwargs):
        # Call the base implementation first to get a context
        context = super().get_context_data(**kwargs)
        # Add in extra data
        book_type = get_object_or_404(BookType, id=self.kwargs["type_id"])
        context["head"] = f"For Type = {book_type.type}"
        return context

peter_lists/books/views/views_publishers.py
from django.views.generic import ListView
from django.shortcuts import get_object_or_404
from peter_lists.books.models import Publisher, Book


class PublisherListView(ListView):
    model = Publisher
    paginate_by = 25
    template_name = "books/publisher_list.html"


class PublisherBookListView(ListView):
    model = Book
    #lookup_url_kwarg = "publisher"
    #lookup_field = "publisher"
    paginate_by = 25
    template_name = "books/book_list.html"

    @property
    def publisher(self):
        return get_object_or_404(Publisher, name=self.kwargs["publisher"])

    def get_queryset(self):
        return Book.books.filter(publisher=self.publisher)

    def get_context_data(self, **kwargs):
        # Call the base implementation first to get a context
        context = super().get_context_data(**kwargs)
        # Add in extra data
        context['head'] = f"For Publisher = {self.publisher}"
        return context

peter_lists/images/views.py
from django.shortcuts import render

# Create your views here.

peter_lists/lego/views.py
from django.shortcuts import render
from django.views.generic import ListView
from.models import LegoSet

# Create your views here.
def LegoHome(request):
    return render(request, "lego/lego_home.html")

class LegoListView(ListView):
    model = LegoSet
    template_name = "lego/lego_list.html"

peter_lists/origami/views.py
from django.shortcuts import render
from django.views.generic import ListView
from .models import OrigamiModel

# Create your views here.
def OrigamiHome(request):
    return render(request, "origami/origami_home.html")

class OrigamiListView(ListView):
    model = OrigamiModel
    template_name = "origami/origami_list.html"

peter_lists/projects/views.py
from django.views.generic import ListView
from django.db.models import Count
from django.shortcuts import render
from ..books.models import Book

# Create your views here.
def ProjHomeView(request):
    return render(request, "projects/home.html")


def ProjAdminView(request):
    return render(request, "projects/home.html")


class ProjTestView(ListView):
    model = Book
    data = Book.books.all().order_by("-author")[:2]
    result = (
        Book.books.values("author__name")
        .order_by("author__name")
        .annotate(count=Count("author__name"))
        .order_by("-count")[:10]
    )
    template_name = "projects/test.html"

    def get_queryset(self):
        # assert False
        return Book.cook_books.all()

peter_lists/templates/books/author_list.html
{% extends "base.html" %}
{% block title %}Author List{% endblock title %}

{% block content %}

  <h2 class="display-2">List of Authors</h2>
  <br/>

  <div class="row">
    <div class="col-sm">
      <b>Author</b>
    </div>
  </div>
  {% for author in page_obj %}
    <div class="row">
      <div class="col-sm">
        <a href="{% url 'books:author_book_list' author.name %}">{{ author.name }}</a>
      </div>
    </div>
  {% endfor %}

  <br/>

  {% include "pagination.html" with page_obj=page_obj %}

  <br/>
  <hr/>

  <br/>
  <p>Don't see an author here?</p>
  <p>
    <a class="btn btn-primary" href="{% url 'books:add' %}" role="button">Add an Author</a>
  </p>

  <p></p>
  <br/>

{% endblock content %}

peter_lists/templates/books/book_detail.html
{% extends "base.html" %}
{% block title %}Books: {{ book.title }}{% endblock title %}

{% block content %}

  <h2>{{ book.title }}</h2>

  {% if book.subtitle %}
    <i>Subtitle:</i>
    <p>{{ book.subtitle }}</p>
  {% endif %}

  {% if book.author %}
    <i>Author:</i>
    <p>{{ book.author }}</p>
  {% endif %}

  <br/>

  {% if book.description %}
    <i>Descripton:</i>
    <p>{{ book.description }}</p>
  {% endif %}

  {% if book.isbn %}
    <i>ISBN:</i>
    <p>{{ book.isbn }}</p>
  {% endif %}

  {% if book.publisher %}
    <i>Publisher:</i>
    <p>{{ book.publisher }}</p>
  {% endif %}

  {% if book.type %}
    <i>Type:</i>
    <p>{{ book.type }}</p>
  {% endif %}

  {% if book.form %}
    <i>Form:</i>
    <p>{{ book.get_form_display }}</p>
  {% endif %}

  {% if book.status %}
    <i>Status:</i>
    <p>{{ book.get_status_display }}</p>
  {% endif %}

  <hr/>

  {% if book.creator %}
    <h3>Submitted by <a href="{{ book.creator.get_absolute_url }}">{{ book.creator.username }}</a></h3>
    {% if book.creator.name %}
      <p>{{ book.creator.name }}</p>
    {% endif %}
  {% endif %}

  <p>
    <a class="btn btn-primary" href="{% url 'books:update' book.slug %}" role="button">Edit Book</a>
  </p>

{% endblock content %}

peter_lists/templates/books/book_form.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% block title %}{{ view.action }} Book{% endblock title %}

{% block content %}
  {% with action=view.action|default:"Add" %}

    <h2 class="display-2">{{ action }} Book</h2>
    <form action="." class="crispy form-horizontal" method="post">
      {% crispy form form.helper %}
    </form>

  {% endwith %}
{% endblock content %}

peter_lists/templates/books/book_list.html
{% extends "base.html" %}
{% block title %}Book List{% endblock title %}

{% block content %}

  <h2 class="display-2">Book List</h2>
  {% if head %}
    <h3>{{ head }}</h3>
    <br/>
  {% endif %}

  <div class="row">
    <div class="col-sm">
      <b>Title</b>
    </div>
    <div class="col-sm">
      <b>Sub-Title</b>
    </div>
    <div class="col-sm">
      <b>Author</b>
    </div>
    <div class="col-sm">
      <b>Publisher</b>
    </div>
    <div class="col-sm">
      <b>Status</b>
    </div>
  </div>

  <hr/>

  {% for book in page_obj %}
    <div class="row">
      <div class="col-sm">
        <a href="{% url 'books:update' book.slug %}">{{ book.title }}</a>
      </div>
      <div class="col-sm">
        {{ book.subtitle }}
      </div>
      <div class="col-sm">
        <a href="{% url 'books:author_book_list' book.author %}">{{ book.author }}</a>
      </div>
      <div class="col-sm">
        <a href="{% url 'books:publisher_book_list' book.publisher %}">{{ book.publisher }}</a>
      </div>
      <div class="col-sm">
        {{ book.get_status_display }}
      </div>
    </div>
  {% endfor %}

  <br/>
  {% include "pagination.html" with page_obj=page_obj %}
  <br/>
  <hr/>

  <div class="row">
    <div class="col-3">
      <p>Don't see a book listed here?</p>
    </div>
    <div class="col-6">
      <p></p>
    </div>
  </div>
  <div class="row">
    <div class="col-3">
      <a class="btn btn-primary" href="{% url 'books:add' %}" role="button">Add Book</a>
    </div>
    <div class="col-6">
      <a class="btn btn-primary" href="{% url 'books:list' %}" role="button">All Books</a>
      <a class="btn btn-primary" href="{% url 'books:author_list' %}" role="button">All Authors</a>
      <a class="btn btn-primary" href="{% url 'books:publishers_list' %}" role="button">All Publishers</a>
      <a class="btn btn-primary" href="{% url 'books:booktype_list' %}" role="button">All Book Types</a>
    </div>
  </div>

  <p></p>
  <br/>

{% endblock content %}

peter_lists/templates/books/books_confirm_delete.html
{% extends "base.html" %}
{% block title %}Delete Book{% endblock title %}

{% block content %}

  <h4 class="display-4">Delete Book</h4>
  <br/>

  <form method="post">{% csrf_token %}
      <p>Are you sure you want to delete "{{ books }}"?</p>
      <input class="btn btn-warning" type="submit" value="Confirm">
  </form>

{% endblock content %}

peter_lists/templates/books/books_home.html
{% extends "base.html" %}
{% block content %}

  <h4 class="display-4">Latest 3 books</h4>

  <p><a class="btn btn-primary" href="{% url 'books:list' %}" role="button">List of all Books</a>
    <a class="btn btn-primary" href="{% url 'books:add' %}" role="button">Add Book</a></p>
  <br/>

  {% for book in books %}
    <h5><a href="{% url 'books:detail' book.slug %}">{{ book.title }}</a></h5>
    <br/>
  {% endfor %}

  <hr/>

  <h4 class="display-4">Latest 3 authors</h4>

  <p><a class="btn btn-primary" href="{% url 'books:author_list' %}" role="button">List of all Authors</a>
    <a class="btn btn-primary" href="{% url 'books:add' %}" role="button">Add Book</a></p>
  <br/>

  {% for author in authors %}
    <h5><a href="{% url 'books:detail' author.id %}">{{ author.name }}</a></h5>
    <br/>
  {% endfor %}

  <hr/>

  <h4 class="display-4">Latest 3 publishers</h4>

  <p><a class="btn btn-primary" href="{% url 'books:publishers_list' %}" role="button">List of all Publishers</a>
    <a class="btn btn-primary" href="{% url 'books:add' %}" role="button">Add Book</a></p>
  <br/>

  {% for publisher in publishers %}
    <h5><a href="{% url 'books:detail' publisher.id %}">{{ publisher.name }}</a></h5>
    <br/>
  {% endfor %}

  <hr/>

{% endblock content %}

peter_lists/templates/books/booktype_list.html
{% extends "base.html" %}
{% block title %}Book Type List{% endblock title %}

{% block content %}

  <h2 class="display-2">List of Book Types</h2>
  <br/>

  <h3>Count by Book Type</h3>
  <div class="row">
    <div class="col-sm">
      <b>Book Type</b>
    </div>
    <div class="col-sm">
      <b>Count</b>
    </div>
  </div>
  <hr/>
  {% for row in view.result %}
    <div class="row">
      <div class="col-sm">
        <a href="{% url 'books:booktype_book_list' row.type %}">{{ row.type__type }}</a>
      </div>
      <div class="col-sm">
        <p>{{ row.count }}</p>
      </div>
    </div>
  {% endfor %}

  </br>

  <h3>Book Type (name order)</h3>
  <div class="row">
    <div class="col-sm">
      <b>Book Type</b>
    </div>
    <div class="col-sm">
      <b>Type Id</b>
    </div>
  </div>
  <hr/>
  {% for type in booktype_list %}
    <div class="row">
      <div class="col-sm">
        <a href="{% url 'books:booktype_book_list' type.id %}">{{ type.type }}</a>
      </div>
      <div class="col-sm">
        <p>{{ type.id }}</p>
      </div>
    </div>
  {% endfor %}

  <br/>
  <hr/>

  <br/>
  <p>Don't see an book type here?</p>
  <p>
    <a class="btn btn-primary" href="{% url 'books:add' %}" role="button">Add a Book Type</a>
  </p>

  <p></p>
  <br/>

{% endblock content %}

peter_lists/templates/books/publisher_list.html
{% extends "base.html" %}
{% block title %}Publisher List{% endblock title %}

{% block content %}

  <h2 class="display-2">List of Publishers</h2>
  <br/>

  <div class="row">
    <div class="col-sm">
      <b>Publisher</b>
    </div>
  </div>
  {% for publisher in page_obj %}
    <div class="row">
      <div class="col-sm">
        <a href="{% url 'books:publisher_book_list' publisher.name %}">{{ publisher.name }}</a>
      </div>
    </div>
  {% endfor %}

  <br/>

  {% include "pagination.html" with page_obj=page_obj %}

  <br/>
  <hr/>

  <br/>
  <p>Don't see an publisher here?</p>
  <p>
    <a class="btn btn-primary" href="{% url 'books:add' %}" role="button">Add an Publisher</a>
  </p>

  <p></p>
  <br/>

{% endblock content %}